name: ci
on: 
  pull_request:
    types:["opened", "synchronize"]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: dtolnay/install@master
      with:
        crate: cargo-sort
    - uses: dtolnay/install@master
      with:
        crate: cargo-nextest
    - run: cargo make lint
    - run: cargo make test
    